import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'AL';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Navbar
    'nav.about': 'About',
    'nav.solutions': 'Solutions',
    'nav.connectivity': 'Connectivity',
    'nav.bedbank': 'Bedbank',
    'nav.global': 'Global',
    'nav.contact': 'Contact',
    'nav.partnerLogin': 'Partner Login',

    // Hero
    'hero.headline': 'Global OTA & Bedbank',
    'hero.subheadline': '30+ years of trust, local strength, and unbeatable inventory in the Western Balkans.',
    'hero.experience': 'B2B Travel Technology Platform',
    'hero.features': 'Direct contracts • Instant booking • 24/7 support',
    'hero.builtFor': 'Built for Travel Agencies, OTAs and DMCs.',
    'hero.becomePartner': 'Become a Partner',
    'hero.readyToConnect': 'Ready to Connect?',

    // About
    'about.badge': 'TRUSTED BY TRAVEL PROFESSIONALS WORLDWIDE',
    'about.title1': "Albania's Leading",
    'about.title2': 'B2B Travel OTA Platform',
    'about.description1': 'VasDream is a B2B travel OTA platform built in the Western Balkans, active since 2015 and backed by over 30 years of hands-on travel industry experience.',
    'about.description2': 'Designed for professional buyers, VasDream provides access to global hotel inventory through a single, reliable platform — supporting travel agencies, tour operators, DMCs, and corporate travel sellers worldwide.',
    'about.description3': 'Our value lies in combining technology with deep regional expertise. With strong local market knowledge, trusted industry relationships, and dedicated support teams, we enable our partners to book confidently, scale efficiently, and access competitive rates across the world.',
    'about.highlight1.title': 'Since 2015',
    'about.highlight1.desc': 'Operating as a dedicated B2B travel OTA platform',
    'about.highlight2.title': '30+ Years Experience',
    'about.highlight2.desc': 'Built on decades of operational travel know-how',
    'about.highlight3.title': '3M+ Hotels Worldwide',
    'about.highlight3.desc': 'Global inventory with real-time availability',
    'about.highlight4.title': 'Known & Respected',
    'about.highlight4.desc': 'A trusted OTA partner across the Balkans and beyond',
    'about.highlight5.title': 'Local Support Teams',
    'about.highlight5.desc': 'Market-level expertise and responsive assistance',
    'about.highlight6.title': 'Long-Term Industry Trust',
    'about.highlight6.desc': 'Sustained partnerships across the travel ecosystem',

    // Solutions
    'solutions.badge': 'OUR SOLUTIONS',
    'solutions.title': 'Our Solutions',
    'solutions.description': 'Everything you need to power your travel business with the Western Balkans\' premier hotel inventory',
    'solutions.globalInventory.title': 'Global Inventory',
    'solutions.globalInventory.description': 'Access 3M+ hotels worldwide through our integrated network of global suppliers and direct contracts.',
    'solutions.extranetAccess.title': 'Extranet Access',
    'solutions.extranetAccess.description': 'Manage bookings, view availability, and control inventory through our intuitive platform.',
    'solutions.apiIntegration.title': 'XML / API Integration',
    'solutions.apiIntegration.description': 'Seamless technical integration with your existing systems via XML or JSON API.',
    'solutions.exclusiveRates.title': 'Exclusive Rates',
    'solutions.exclusiveRates.description': 'Preferential pricing unavailable on public channels, maximizing your margins.',
    'solutions.support.title': '24/7 Multilingual Support',
    'solutions.support.description': 'Round-the-clock assistance in multiple languages whenever you need it.',
    'solutions.advancedFilters.title': 'Advanced Filtering',
    'solutions.advancedFilters.description': 'Search and filter by destination, category, board type, and more.',
    'solutions.serving': 'Serving Travel Professionals Worldwide',
    'solutions.otas': 'OTAs',
    'solutions.dmcs': 'DMCs',
    'solutions.agencies': 'Agencies',
    'solutions.corporate': 'Corporate',

    // Connectivity
    'connectivity.title': 'Seamless Integration Ecosystem',
    'connectivity.description': 'Connect your systems to the world\'s leading travel technology platforms',
    'connectivity.yourSystem': 'Your System',
    'connectivity.yourSystemDesc': 'All major platforms connected with multiple integration methods',
    'connectivity.vasdream': 'VasDream',
    'connectivity.apiGateway': 'API Gateway',
    'connectivity.hotelInventory': 'Hotel Inventory',
    'connectivity.hotelsWorldwide': '3M+ Hotels Worldwide',
    'connectivity.connectedPlatforms': 'Connected Platforms',
    'connectivity.xmlJsonApi': 'XML & JSON API',
    'connectivity.uptimeSla': '99.9% Uptime SLA',
    'connectivity.sslSecured': 'SSL Secured',

    // Bedbank
    'bedbank.badge': 'NOW LIVE',
    'bedbank.badgeText': 'New Feature',
    'bedbank.title': 'VasDream Bedbank',
    'bedbank.subtitle': 'The only dedicated bedbank in Albania — powered by our exclusive portfolio of',
    'bedbank.subtitleHighlight': '6,500+ directly contracted hotels',
    'bedbank.description': 'Whether you\'re an OTA scaling your Balkan inventory, a DMC seeking reliable supply, or a regional wholesaler expanding your reach, VasDream Bedbank delivers transparent availability and strong margins through API or Extranet.',
    'bedbank.getStarted': 'Get Started',
    'bedbank.availableVia': 'Available via API & Extranet',
    'bedbank.feature1.title': '6,500+ Direct Contracts',
    'bedbank.feature1.desc': 'Albania, Montenegro, Greece & the Balkans — all directly contracted.',
    'bedbank.feature2.title': 'Transparent Availability',
    'bedbank.feature2.desc': 'Real-time rates and inventory with strong margins for your business.',
    'bedbank.feature3.title': 'Distribution Flexibility',
    'bedbank.feature3.desc': 'Access via API integration or through our intuitive Extranet platform.',
    'bedbank.feature4.title': 'Perfect For Your Business',
    'bedbank.feature4.desc': 'Ideal for OTAs, DMCs, and regional wholesalers seeking quality inventory.',
    'bedbank.hotelTitle': 'Are you a hotel?',
    'bedbank.hotelDesc': 'Join our distribution network and unlock access to a global network of travel buyers. List your property with VasDream Bedbank and benefit from:',
    'bedbank.hotelBenefit1': 'Global distribution to 1000+ B2B partners worldwide',
    'bedbank.hotelBenefit2': 'Access to travel agencies, OTAs, and tour operators',
    'bedbank.hotelBenefit3': 'Competitive commission structures with transparent pricing',
    'bedbank.hotelBenefit4': 'Dedicated account management and 24/7 support',
    'bedbank.startHere': 'Start Here',
    'bedbank.formTitle': 'List Your Hotel',
    'bedbank.formDesc': 'Fill in your details and our representatives will contact you within 24 hours to discuss partnership opportunities.',
    'bedbank.formHotelName': 'Hotel Name',
    'bedbank.formContactName': 'Contact Name',
    'bedbank.formEmail': 'Email',
    'bedbank.formPhone': 'Phone',
    'bedbank.formLocation': 'Location',
    'bedbank.formRooms': 'Number of Rooms',
    'bedbank.formSubmit': 'Submit Request',

    // Who We Serve
    'serve.title': 'Who We Serve',
    'serve.description': 'Tailored solutions for every travel business model',
    'serve.agencies': 'Travel Agencies',
    'serve.otas': 'OTAs & Wholesalers',
    'serve.corporate': 'Corporate',
    'serve.tech': 'Tech Integrators',
    'serve.agencies.title': 'Full margin control with dedicated support',
    'serve.agencies.desc': 'Access competitive B2B rates with transparent pricing that lets you maintain healthy margins. Every agency partner gets a dedicated account manager who understands your business.',
    'serve.agencies.feature1': 'Margin control tools',
    'serve.agencies.feature2': 'Dedicated account manager',
    'serve.agencies.feature3': 'White-label booking solutions',
    'serve.agencies.feature4': 'Competitive B2B rates',
    'serve.otas.title': 'Volume access with seamless API connection',
    'serve.otas.desc': 'Built for high-volume operations with robust API infrastructure. Scale your Balkan inventory without infrastructure concerns — our platform handles thousands of requests effortlessly.',
    'serve.otas.feature1': 'High-volume API access',
    'serve.otas.feature2': 'Bulk rate management',
    'serve.otas.feature3': 'Real-time availability',
    'serve.otas.feature4': 'Automated booking flow',
    'serve.corporate.title': 'Clean dashboard with special corporate rates',
    'serve.corporate.desc': 'Streamline business travel with our corporate booking platform. Access negotiated rates, manage policies, and get detailed reporting for finance teams.',
    'serve.corporate.feature1': 'Corporate rate programs',
    'serve.corporate.feature2': 'Clean booking dashboard',
    'serve.corporate.feature3': 'Policy management',
    'serve.corporate.feature4': 'Travel expense reporting',
    'serve.tech.title': 'API-ready with scalable architecture',
    'serve.tech.desc': 'Developer-first approach with comprehensive documentation and a scalable design that grows with your platform. XML and JSON support for maximum flexibility.',
    'serve.tech.feature1': 'RESTful & SOAP APIs',
    'serve.tech.feature2': 'Comprehensive documentation',
    'serve.tech.feature3': 'Scalable architecture',
    'serve.tech.feature4': '24/7 technical support',

    // Global
    'global.badge': 'GLOBAL PRESENCE',
    'global.title': 'Offices Worldwide',
    'global.description': 'With strategic locations across Europe and the Middle East, we provide local expertise with global reach.',
    'global.headquarters': 'Headquarters',
    'global.office': 'Office',
    'global.trustedBy': 'Trusted by Industry Leaders',
    'global.andMore': 'and many more',

    // Testimonials
    'testimonials.title': 'What Partners Say',

    // Buyers Network
    'buyers.badge': 'GROWING NETWORK',
    'buyers.title': 'Our Expanding Network of Buyers',
    'buyers.description': 'Trusted by leading travel companies worldwide who rely on VasDream for quality hotel inventory and competitive rates.',
    'buyers.andGrowing': '...and our network keeps growing every month.',

    // CTA
    'cta.title': 'Ready to Connect?',
    'cta.description': 'Join 1000+ partners who rely on VasDream for trusted hotel supply, with instant booking and unbeatable service.',
    'cta.feature1': 'No setup fees',
    'cta.feature2': '24/7 support',
    'cta.feature3': 'Multi-language support (EN / AL)',
    'cta.becomePartner': 'Become a Partner',
    'cta.explorePlatform': 'Explore Platform',

    // Footer
    'footer.description': 'Connecting travel businesses to 3M+ hotels across 190+ countries with cutting-edge API technology.',
    'footer.travelAgencies': 'Travel Agencies',
    'footer.otasDmcs': 'OTAs, DMCs, Tour Operators & Tech Platforms',
    'footer.company': 'Company',
    'footer.careers': 'Careers',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.cookiesPolicy': 'Cookies Policy',
    'footer.newsletter': 'Subscribe to Newsletter',
    'footer.newsletterDesc': 'Stay updated with the latest news and offers.',
    'footer.emailPlaceholder': 'Enter your email',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved.',
    'footer.apiStatus': 'API Status: Operational',

    // Partner Modal
    'partner.title': 'Become a Partner',
    'partner.subtitle': 'Choose how you want to connect with VasDream',
    'partner.agencyTitle': 'Travel Agency',
    'partner.agencyDesc': 'Get access to our booking platform with exclusive B2B rates and dedicated support.',
    'partner.apiTitle': 'API Integration',
    'partner.apiDesc': 'Connect your systems directly via XML or JSON API for automated booking flow.',
    'partner.back': 'Back to selection',
    'partner.companyName': 'Company Name',
    'partner.contactName': 'Contact Name',
    'partner.email': 'Email',
    'partner.phone': 'Phone',
    'partner.website': 'Website',
    'partner.message': 'Message (Optional)',
    'partner.submit': 'Submit Request',
    'partner.submitting': 'Submitting...',
    'partner.thankYouTitle': 'Thank You!',
    'partner.thankYouDesc': 'Your request has been received. Our team will contact you shortly.',
    'partner.close': 'Close',

    // Login Modal
    'login.title': 'Partner Login',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.forgotPassword': 'Forgot password?',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Register here',

    // Legal - shared
    'legal.backHome': '← Back to Home',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last updated',
    'privacy.section1.title': '1. Introduction',
    'privacy.section1.content': 'VasDream ("we", "us", or "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website vasdream.com and use our B2B travel platform services. We operate in compliance with applicable data protection laws, including the GDPR.',
    'privacy.section2.title': '2. Information We Collect',
    'privacy.section2.content': 'We may collect the following types of information:',
    'privacy.section2.item1': 'Business contact information (company name, name, email, phone number)',
    'privacy.section2.item2': 'Account credentials for platform access',
    'privacy.section2.item3': 'Booking and transaction data related to hotel reservations',
    'privacy.section2.item4': 'Technical data such as IP address, browser type, and usage analytics',
    'privacy.section3.title': '3. How We Use Your Information',
    'privacy.section3.content': 'We use the collected information for the following purposes:',
    'privacy.section3.item1': 'To provide and maintain our B2B travel platform services',
    'privacy.section3.item2': 'To process hotel bookings and reservations on your behalf',
    'privacy.section3.item3': 'To communicate with you about your account, bookings, and support requests',
    'privacy.section3.item4': 'To send newsletters and marketing communications (with your consent)',
    'privacy.section4.title': '4. Data Sharing & Third Parties',
    'privacy.section4.content': 'We share your information only with hotel suppliers and connectivity partners necessary to fulfill bookings. We do not sell your personal data. Third-party service providers who assist our operations are bound by contractual obligations to protect your data.',
    'privacy.section5.title': '5. Data Retention',
    'privacy.section5.content': 'We retain your personal data for as long as your business account is active or as needed to provide you services. Booking records are retained for the legally required period for tax and compliance purposes. You may request deletion of your data at any time by contacting us.',
    'privacy.section6.title': '6. Your Rights',
    'privacy.section6.content': 'Under applicable data protection laws, you have the right to:',
    'privacy.section6.item1': 'Access the personal data we hold about you',
    'privacy.section6.item2': 'Request correction of inaccurate data',
    'privacy.section6.item3': 'Request deletion of your personal data',
    'privacy.section6.item4': 'Object to or restrict processing of your data',
    'privacy.section7.title': '7. Data Security',
    'privacy.section7.content': 'We implement industry-standard security measures including SSL encryption, secure API connections, and access controls to protect your data. Our platform maintains a 99.9% uptime SLA with enterprise-grade infrastructure.',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.content': 'If you have questions about this Privacy Policy or wish to exercise your data rights, please contact us:',
    'privacy.contact.address': 'Rruga Dervish Shaba, Tirana, Albania, 1019',

    // Cookies Policy
    'cookies.title': 'Cookies Policy',
    'cookies.lastUpdated': 'Last updated',
    'cookies.section1.title': '1. What Are Cookies',
    'cookies.section1.content': 'Cookies are small text files stored on your device when you visit our website. They help us provide you with a better experience by remembering your preferences, analyzing site usage, and enabling certain functionalities of our B2B travel platform.',
    'cookies.section2.title': '2. Types of Cookies We Use',
    'cookies.section2.content': 'We use the following categories of cookies on vasdream.com:',
    'cookies.type1.title': 'Essential Cookies',
    'cookies.type1.desc': 'Required for the website to function properly. These include session cookies for authentication, language preferences, and security tokens. These cannot be disabled.',
    'cookies.type2.title': 'Performance & Analytics Cookies',
    'cookies.type2.desc': 'Help us understand how visitors interact with our website by collecting anonymous usage data. This helps us improve our platform and user experience.',
    'cookies.type3.title': 'Functional Cookies',
    'cookies.type3.desc': 'Enable enhanced functionality and personalization, such as remembering your login details, preferred language (EN/AL), and display preferences.',
    'cookies.type4.title': 'Marketing Cookies',
    'cookies.type4.desc': 'Used to track visitors across websites to display relevant advertisements. We use these sparingly and only with your consent.',
    'cookies.section3.title': '3. Managing Cookies',
    'cookies.section3.content': 'You can control and manage cookies through your browser settings. Most browsers allow you to refuse or delete cookies. However, disabling essential cookies may affect the functionality of our platform, including login and booking features.',
    'cookies.section4.title': '4. Third-Party Cookies',
    'cookies.section4.content': 'Some cookies on our site are placed by third-party services we use, such as analytics providers (e.g., Google Analytics) and social media platforms (LinkedIn, Instagram). These third parties have their own privacy policies governing how they use your data.',
    'cookies.section5.title': '5. Updates to This Policy',
    'cookies.section5.content': 'We may update this Cookies Policy from time to time to reflect changes in technology, legislation, or our business practices. Any changes will be posted on this page with an updated revision date.',
    'cookies.contact.title': 'Contact Us',
    'cookies.contact.content': 'If you have questions about our use of cookies, please contact us:',
    'cookies.contact.address': 'Rruga Dervish Shaba, Tirana, Albania, 1019',
  },
  AL: {
    // Navbar
    'nav.about': 'Rreth Nesh',
    'nav.solutions': 'Zgjidhjet',
    'nav.connectivity': 'Lidhja',
    'nav.bedbank': 'Bedbank',
    'nav.global': 'Global',
    'nav.contact': 'Kontakt',
    'nav.partnerLogin': 'Hyrje Partneri',

    // Hero
    'hero.headline': 'OTA & Bedbank Global',
    'hero.subheadline': '30+ vjet besim, forcë lokale dhe inventar i paarritshëm në Ballkanin Perëndimor.',
    'hero.experience': 'Platformë Teknologjike B2B për Udhëtime',
    'hero.features': 'Kontrata direkte • Rezervim i menjëhershëm • Mbështetje 24/7',
    'hero.builtFor': 'Ndërtuar për Agjenci Udhëtimi, OTA dhe DMC.',
    'hero.becomePartner': 'Bëhu Partner',
    'hero.readyToConnect': 'Gati për t\'u Lidhur?',

    // About
    'about.badge': 'E BESUAR NGA PROFESIONISTËT E UDHËTIMEVE NË MBARË BOTËN',
    'about.title1': 'Platforma Kryesore e Shqipërisë',
    'about.title2': 'B2B Travel OTA',
    'about.description1': 'VasDream është një platformë B2B travel OTA e ndërtuar në Ballkanin Perëndimor, aktive që nga 2015 dhe e mbështetur nga mbi 30 vjet përvojë praktike në industrinë e udhëtimeve.',
    'about.description2': 'E dizajnuar për blerës profesionistë, VasDream ofron qasje në inventar global hotelesh përmes një platforme të vetme dhe të besueshme — duke mbështetur agjencitë e udhëtimit, operatorët turistikë, DMC-të dhe shitësit e udhëtimeve korporative në mbarë botën.',
    'about.description3': 'Vlera jonë qëndron në kombinimin e teknologjisë me ekspertizën e thellë rajonale. Me njohuri të forta të tregut lokal, marrëdhënie të besuara në industri dhe ekipe mbështetjeje të dedikuara, ne mundësojmë partnerët tanë të rezervojnë me besim, të shkallëzohen me efikasitet dhe të kenë qasje në çmime konkurruese në mbarë botën.',
    'about.highlight1.title': 'Që nga 2015',
    'about.highlight1.desc': 'Operim si platformë e dedikuar B2B travel OTA',
    'about.highlight2.title': '30+ Vjet Përvojë',
    'about.highlight2.desc': 'E ndërtuar mbi dekada njohurish operative udhëtimi',
    'about.highlight3.title': '3M+ Hotele Botërisht',
    'about.highlight3.desc': 'Inventar global me disponueshmëri në kohë reale',
    'about.highlight4.title': 'I Njohur & I Respektuar',
    'about.highlight4.desc': 'Partner OTA i besuar në Ballkan dhe më gjerë',
    'about.highlight5.title': 'Ekipe Mbështetjeje Lokale',
    'about.highlight5.desc': 'Ekspertizë në nivel tregu dhe ndihmë e përgjegjshme',
    'about.highlight6.title': 'Besim Afatgjatë në Industri',
    'about.highlight6.desc': 'Partneritete të qëndrueshme në ekosistemin e udhëtimeve',

    // Solutions
    'solutions.badge': 'ZGJIDHJET TONA',
    'solutions.title': 'Zgjidhjet Tona',
    'solutions.description': 'Gjithçka që ju nevojitet për të fuqizuar biznesin tuaj të udhëtimit me inventarin kryesor të hoteleve të Ballkanit Perëndimor',
    'solutions.globalInventory.title': 'Inventar Global',
    'solutions.globalInventory.description': 'Qasje në 3M+ hotele në mbarë botën përmes rrjetit tonë të integruar të furnitorëve globalë dhe kontratave direkte.',
    'solutions.extranetAccess.title': 'Qasje Extranet',
    'solutions.extranetAccess.description': 'Menaxhoni rezervimet, shikoni disponueshmërinë dhe kontrolloni inventarin përmes platformës sonë intuitive.',
    'solutions.apiIntegration.title': 'Integrim XML / API',
    'solutions.apiIntegration.description': 'Integrim teknik i pandërprerë me sistemet tuaja ekzistuese përmes XML ose JSON API.',
    'solutions.exclusiveRates.title': 'Çmime Ekskluzive',
    'solutions.exclusiveRates.description': 'Çmime preferenciale të padisponueshme në kanalet publike, duke maksimizuar marzhet tuaja.',
    'solutions.support.title': 'Mbështetje 24/7 Shumëgjuhëshe',
    'solutions.support.description': 'Ndihmë gjatë gjithë kohës në shumë gjuhë kur ju nevojitet.',
    'solutions.advancedFilters.title': 'Filtrim i Avancuar',
    'solutions.advancedFilters.description': 'Kërkoni dhe filtroni sipas destinacionit, kategorisë, llojit të bordit dhe më shumë.',
    'solutions.serving': 'Duke Shërbyer Profesionistët e Udhëtimit në Mbarë Botën',
    'solutions.otas': 'OTA',
    'solutions.dmcs': 'DMC',
    'solutions.agencies': 'Agjenci',
    'solutions.corporate': 'Korporata',

    // Connectivity
    'connectivity.title': 'Ekosistem Integrimi i Pandërprerë',
    'connectivity.description': 'Lidhni sistemet tuaja me platformat kryesore teknologjike të udhëtimit në botë',
    'connectivity.yourSystem': 'Sistemi Juaj',
    'connectivity.yourSystemDesc': 'Të gjitha platformat kryesore të lidhura me metoda të shumta integrimi',
    'connectivity.vasdream': 'VasDream',
    'connectivity.apiGateway': 'Porta API',
    'connectivity.hotelInventory': 'Inventari i Hoteleve',
    'connectivity.hotelsWorldwide': '3M+ Hotele në Mbarë Botën',
    'connectivity.connectedPlatforms': 'Platformat e Lidhura',
    'connectivity.xmlJsonApi': 'XML & JSON API',
    'connectivity.uptimeSla': '99.9% SLA Kohë Funksionimi',
    'connectivity.sslSecured': 'I Siguruar me SSL',

    // Bedbank
    'bedbank.badge': 'TANI LIVE',
    'bedbank.badgeText': 'Veçori e Re',
    'bedbank.title': 'VasDream Bedbank',
    'bedbank.subtitle': 'I vetmi bedbank i dedikuar në Shqipëri — i fuqizuar nga portofoli ynë ekskluziv i',
    'bedbank.subtitleHighlight': '6,500+ hoteleve të kontraktuara direkt',
    'bedbank.description': 'Qoftë jeni OTA që zgjeroni inventarin tuaj Ballkanik, DMC që kërkoni furnizim të besueshëm, ose shitës rajonal me shumicë që zgjeroni shtrirjen tuaj, VasDream Bedbank ofron disponueshmëri transparente dhe marzhe të forta përmes API ose Extranet.',
    'bedbank.getStarted': 'Filloni',
    'bedbank.availableVia': 'I disponueshëm përmes API & Extranet',
    'bedbank.feature1.title': '6,500+ Kontrata Direkte',
    'bedbank.feature1.desc': 'Shqipëri, Mal i Zi, Greqi & Ballkani — të gjitha të kontraktuara direkt.',
    'bedbank.feature2.title': 'Disponueshmëri Transparente',
    'bedbank.feature2.desc': 'Çmime dhe inventar në kohë reale me marzhe të forta për biznesin tuaj.',
    'bedbank.feature3.title': 'Fleksibilitet Shpërndarjeje',
    'bedbank.feature3.desc': 'Qasje përmes integrimit API ose përmes platformës sonë intuitive Extranet.',
    'bedbank.feature4.title': 'Perfekt Për Biznesin Tuaj',
    'bedbank.feature4.desc': 'Ideal për OTA, DMC dhe shitës rajonalë me shumicë që kërkojnë inventar cilësor.',
    'bedbank.hotelTitle': 'Jeni hotel?',
    'bedbank.hotelDesc': 'Bashkohuni me rrjetin tonë të shpërndarjes dhe zhbllokoni qasjen në një rrjet global blerësish udhëtimi. Listoni pronën tuaj me VasDream Bedbank dhe përfitoni nga:',
    'bedbank.hotelBenefit1': 'Shpërndarje globale te 1000+ partnerë B2B në mbarë botën',
    'bedbank.hotelBenefit2': 'Qasje në agjenci udhëtimi, OTA dhe operatorë turne',
    'bedbank.hotelBenefit3': 'Struktura komisioni konkurruese me çmime transparente',
    'bedbank.hotelBenefit4': 'Menaxhim i dedikuar i llogarisë dhe mbështetje 24/7',
    'bedbank.startHere': 'Filloni Këtu',
    'bedbank.formTitle': 'Listoni Hotelin Tuaj',
    'bedbank.formDesc': 'Plotësoni detajet tuaja dhe përfaqësuesit tanë do t\'ju kontaktojnë brenda 24 orëve për të diskutuar mundësitë e partneritetit.',
    'bedbank.formHotelName': 'Emri i Hotelit',
    'bedbank.formContactName': 'Emri i Kontaktit',
    'bedbank.formEmail': 'Email',
    'bedbank.formPhone': 'Telefon',
    'bedbank.formLocation': 'Vendndodhja',
    'bedbank.formRooms': 'Numri i Dhomave',
    'bedbank.formSubmit': 'Dorëzoni Kërkesën',

    // Who We Serve
    'serve.title': 'Kujt i Shërbejmë',
    'serve.description': 'Zgjidhje të personalizuara për çdo model biznesi udhëtimi',
    'serve.agencies': 'Agjenci Udhëtimi',
    'serve.otas': 'OTA & Shitës me Shumicë',
    'serve.corporate': 'Korporata',
    'serve.tech': 'Integrues Teknologjikë',
    'serve.agencies.title': 'Kontroll i plotë i marzheve me mbështetje të dedikuar',
    'serve.agencies.desc': 'Qasje në çmime konkurruese B2B me çmime transparente që ju lejojnë të mbani marzhe të shëndetshme. Çdo partner agjenci merr një menaxher llogarie të dedikuar që kupton biznesin tuaj.',
    'serve.agencies.feature1': 'Mjete kontrolli marzhesh',
    'serve.agencies.feature2': 'Menaxher llogarie i dedikuar',
    'serve.agencies.feature3': 'Zgjidhje rezervimi white-label',
    'serve.agencies.feature4': 'Çmime konkurruese B2B',
    'serve.otas.title': 'Qasje në vëllim me lidhje API të pandërprerë',
    'serve.otas.desc': 'Ndërtuar për operacione me vëllim të lartë me infrastrukturë API të fuqishme. Zgjeroni inventarin tuaj Ballkanik pa shqetësime infrastrukture — platforma jonë trajton mijëra kërkesa pa mundim.',
    'serve.otas.feature1': 'Qasje API me vëllim të lartë',
    'serve.otas.feature2': 'Menaxhim i çmimeve në masë',
    'serve.otas.feature3': 'Disponueshmëri në kohë reale',
    'serve.otas.feature4': 'Rrjedhë rezervimi e automatizuar',
    'serve.corporate.title': 'Panel i pastër me çmime speciale korporative',
    'serve.corporate.desc': 'Thjeshtësoni udhëtimet e biznesit me platformën tonë të rezervimeve korporative. Qasje në çmime të negociuara, menaxhoni politikat dhe merrni raportim të detajuar për ekipet financiare.',
    'serve.corporate.feature1': 'Programe çmimesh korporative',
    'serve.corporate.feature2': 'Panel rezervimi i pastër',
    'serve.corporate.feature3': 'Menaxhim politikash',
    'serve.corporate.feature4': 'Raportim shpenzimesh udhëtimi',
    'serve.tech.title': 'I gatshëm për API me arkitekturë të shkallëzueshme',
    'serve.tech.desc': 'Qasje developer-first me dokumentacion gjithëpërfshirës dhe dizajn të shkallëzueshëm që rritet me platformën tuaj. Mbështetje XML dhe JSON për fleksibilitet maksimal.',
    'serve.tech.feature1': 'API RESTful & SOAP',
    'serve.tech.feature2': 'Dokumentacion gjithëpërfshirës',
    'serve.tech.feature3': 'Arkitekturë e shkallëzueshme',
    'serve.tech.feature4': 'Mbështetje teknike 24/7',

    // Global
    'global.badge': 'PREZENCË GLOBALE',
    'global.title': 'Zyra në Mbarë Botën',
    'global.description': 'Me vendndodhje strategjike në Evropë dhe Lindjen e Mesme, ne ofrojmë ekspertizë lokale me shtrirje globale.',
    'global.headquarters': 'Seli Qendrore',
    'global.office': 'Zyrë',
    'global.trustedBy': 'Të Besuar nga Liderët e Industrisë',
    'global.andMore': 'dhe shumë të tjerë',

    // Testimonials
    'testimonials.title': 'Çfarë Thonë Partnerët',

    // Buyers Network
    'buyers.badge': 'RRJET NË RRITJE',
    'buyers.title': 'Rrjeti Ynë në Zgjerim i Blerësve',
    'buyers.description': 'I besuar nga kompani udhëtimi kryesore në mbarë botën që mbështeten te VasDream për inventar cilësor hotelesh dhe çmime konkurruese.',
    'buyers.andGrowing': '...dhe rrjeti ynë vazhdon të rritet çdo muaj.',

    // CTA
    'cta.title': 'Gati për t\'u Lidhur?',
    'cta.description': 'Bashkohuni me 1000+ partnerë që mbështeten te VasDream për furnizim të besuar hotelesh, me rezervim të menjëhershëm dhe shërbim të paarritshëm.',
    'cta.feature1': 'Pa tarifa vendosjeje',
    'cta.feature2': 'Mbështetje 24/7',
    'cta.feature3': 'Mbështetje shumëgjuhëshe (EN / AL)',
    'cta.becomePartner': 'Bëhu Partner',
    'cta.explorePlatform': 'Eksploroni Platformën',

    // Footer
    'footer.description': 'Duke lidhur bizneset e udhëtimit me 3M+ hotele në 190+ vende me teknologji API të avancuar.',
    'footer.travelAgencies': 'Agjenci Udhëtimi',
    'footer.otasDmcs': 'OTA, DMC, Operatorë Turne & Platforma Teknologjike',
    'footer.company': 'Kompania',
    'footer.careers': 'Karriera',
    'footer.contact': 'Kontakt',
    'footer.legal': 'Ligjore',
    'footer.privacyPolicy': 'Politika e Privatësisë',
    'footer.cookiesPolicy': 'Politika e Cookies',
    'footer.newsletter': 'Abonohuni në Buletinin',
    'footer.newsletterDesc': 'Qëndroni të përditësuar me lajmet dhe ofertat më të fundit.',
    'footer.emailPlaceholder': 'Shkruani email-in tuaj',
    'footer.subscribe': 'Abonohu',
    'footer.rights': 'Të gjitha të drejtat e rezervuara.',
    'footer.apiStatus': 'Statusi API: Operacional',

    // Partner Modal
    'partner.title': 'Bëhu Partner',
    'partner.subtitle': 'Zgjidhni si dëshironi të lidheni me VasDream',
    'partner.agencyTitle': 'Agjenci Udhëtimi',
    'partner.agencyDesc': 'Merrni qasje në platformën tonë të rezervimeve me çmime ekskluzive B2B dhe mbështetje të dedikuar.',
    'partner.apiTitle': 'Integrim API',
    'partner.apiDesc': 'Lidhni sistemet tuaja direkt përmes XML ose JSON API për rrjedhë të automatizuar rezervimesh.',
    'partner.back': 'Kthehu te përzgjedhja',
    'partner.companyName': 'Emri i Kompanisë',
    'partner.contactName': 'Emri i Kontaktit',
    'partner.email': 'Email',
    'partner.phone': 'Telefon',
    'partner.website': 'Faqja e Internetit',
    'partner.message': 'Mesazh (Opsional)',
    'partner.submit': 'Dorëzoni Kërkesën',
    'partner.submitting': 'Duke dorëzuar...',
    'partner.thankYouTitle': 'Faleminderit!',
    'partner.thankYouDesc': 'Kërkesa juaj është marrë. Ekipi ynë do t\'ju kontaktojë së shpejti.',
    'partner.close': 'Mbyll',

    // Login Modal
    'login.title': 'Hyrje Partneri',
    'login.email': 'Email',
    'login.password': 'Fjalëkalimi',
    'login.submit': 'Hyni',
    'login.forgotPassword': 'Keni harruar fjalëkalimin?',
    'login.noAccount': 'Nuk keni llogari?',
    'login.register': 'Regjistrohuni këtu',

    // Legal - shared
    'legal.backHome': '← Kthehu në Faqen Kryesore',

    // Privacy Policy
    'privacy.title': 'Politika e Privatësisë',
    'privacy.lastUpdated': 'Përditësuar së fundmi',
    'privacy.section1.title': '1. Hyrje',
    'privacy.section1.content': 'VasDream ("ne", "jonë") është e përkushtuar në mbrojtjen e privatësisë suaj. Kjo Politikë Privatësie shpjegon si mbledhim, përdorim, zbulojmë dhe mbrojmë informacionin tuaj kur vizitoni faqen tonë vasdream.com dhe përdorni shërbimet tona të platformës B2B të udhëtimit. Ne operojmë në përputhje me ligjet e zbatueshme të mbrojtjes së të dhënave, përfshirë GDPR.',
    'privacy.section2.title': '2. Informacioni që Mbledhim',
    'privacy.section2.content': 'Ne mund të mbledhim llojet e mëposhtme të informacionit:',
    'privacy.section2.item1': 'Informacion kontakti biznesi (emri i kompanisë, emri, email, numri i telefonit)',
    'privacy.section2.item2': 'Kredencialet e llogarisë për qasje në platformë',
    'privacy.section2.item3': 'Të dhëna rezervimi dhe transaksionesh lidhur me rezervimet e hoteleve',
    'privacy.section2.item4': 'Të dhëna teknike si adresa IP, lloji i shfletuesit dhe analitika e përdorimit',
    'privacy.section3.title': '3. Si e Përdorim Informacionin Tuaj',
    'privacy.section3.content': 'Ne e përdorim informacionin e mbledhur për qëllimet e mëposhtme:',
    'privacy.section3.item1': 'Për të ofruar dhe mirëmbajtuar shërbimet tona të platformës B2B të udhëtimit',
    'privacy.section3.item2': 'Për të përpunuar rezervimet e hoteleve në emrin tuaj',
    'privacy.section3.item3': 'Për të komunikuar me ju rreth llogarisë, rezervimeve dhe kërkesave për mbështetje',
    'privacy.section3.item4': 'Për të dërguar buletine dhe komunikime marketingu (me pëlqimin tuaj)',
    'privacy.section4.title': '4. Ndarja e të Dhënave & Palët e Treta',
    'privacy.section4.content': 'Ne ndajmë informacionin tuaj vetëm me furnitorët e hoteleve dhe partnerët e lidhshmërisë të nevojshme për përmbushjen e rezervimeve. Ne nuk shesim të dhënat tuaja personale. Ofruesit e shërbimeve të palëve të treta që ndihmojnë operacionet tona janë të lidhur me detyrime kontraktuale për mbrojtjen e të dhënave tuaja.',
    'privacy.section5.title': '5. Ruajtja e të Dhënave',
    'privacy.section5.content': 'Ne ruajmë të dhënat tuaja personale për aq kohë sa llogaria juaj e biznesit është aktive ose sipas nevojës për t\'ju ofruar shërbime. Regjistrat e rezervimeve ruhen për periudhën e kërkuar ligjërisht për qëllime tatimore dhe pajtueshmërie. Ju mund të kërkoni fshirjen e të dhënave tuaja në çdo kohë duke na kontaktuar.',
    'privacy.section6.title': '6. Të Drejtat Tuaja',
    'privacy.section6.content': 'Sipas ligjeve të zbatueshme të mbrojtjes së të dhënave, ju keni të drejtë të:',
    'privacy.section6.item1': 'Qaseni në të dhënat personale që mbajmë rreth jush',
    'privacy.section6.item2': 'Kërkoni korrigjimin e të dhënave të pasakta',
    'privacy.section6.item3': 'Kërkoni fshirjen e të dhënave tuaja personale',
    'privacy.section6.item4': 'Kundërshtoni ose kufizoni përpunimin e të dhënave tuaja',
    'privacy.section7.title': '7. Siguria e të Dhënave',
    'privacy.section7.content': 'Ne zbatojmë masa sigurie sipas standardeve të industrisë duke përfshirë enkriptimin SSL, lidhje të sigurta API dhe kontrolle qasje për mbrojtjen e të dhënave tuaja. Platforma jonë mirëmban një SLA kohë funksionimi 99.9% me infrastrukturë të nivelit enterprise.',
    'privacy.contact.title': 'Na Kontaktoni',
    'privacy.contact.content': 'Nëse keni pyetje rreth kësaj Politike Privatësie ose dëshironi të ushtroni të drejtat tuaja mbi të dhënat, ju lutem na kontaktoni:',
    'privacy.contact.address': 'Rruga Dervish Shaba, Tiranë, Shqipëri, 1019',

    // Cookies Policy
    'cookies.title': 'Politika e Cookies',
    'cookies.lastUpdated': 'Përditësuar së fundmi',
    'cookies.section1.title': '1. Çfarë Janë Cookies',
    'cookies.section1.content': 'Cookies janë skedarë të vegjël teksti që ruhen në pajisjen tuaj kur vizitoni faqen tonë. Ato na ndihmojnë t\'ju ofrojmë një përvojë më të mirë duke mbajtur mend preferencat tuaja, duke analizuar përdorimin e faqes dhe duke mundësuar funksionalitete të caktuara të platformës sonë B2B të udhëtimit.',
    'cookies.section2.title': '2. Llojet e Cookies që Përdorim',
    'cookies.section2.content': 'Ne përdorim kategoritë e mëposhtme të cookies në vasdream.com:',
    'cookies.type1.title': 'Cookies Thelbësore',
    'cookies.type1.desc': 'Të nevojshme që faqja të funksionojë saktë. Këto përfshijnë cookies sesioni për autentikim, preferencat e gjuhës dhe tokenat e sigurisë. Këto nuk mund të çaktivizohen.',
    'cookies.type2.title': 'Cookies Performancë & Analitike',
    'cookies.type2.desc': 'Na ndihmojnë të kuptojmë si ndërveprojnë vizitorët me faqen tonë duke mbledhur të dhëna anonime përdorimi. Kjo na ndihmon të përmirësojmë platformën dhe përvojën e përdoruesit.',
    'cookies.type3.title': 'Cookies Funksionale',
    'cookies.type3.desc': 'Mundësojnë funksionalitet të avancuar dhe personalizim, si mbajtja mend e detajeve të hyrjes, gjuhës së preferuar (EN/AL) dhe preferencave të shfaqjes.',
    'cookies.type4.title': 'Cookies Marketingu',
    'cookies.type4.desc': 'Përdoren për gjurmimin e vizitorëve nëpër faqe për shfaqjen e reklamave relevante. Ne i përdorim këto me masë dhe vetëm me pëlqimin tuaj.',
    'cookies.section3.title': '3. Menaxhimi i Cookies',
    'cookies.section3.content': 'Ju mund të kontrolloni dhe menaxhoni cookies përmes cilësimeve të shfletuesit tuaj. Shumica e shfletuesve ju lejojnë të refuzoni ose fshini cookies. Megjithatë, çaktivizimi i cookies thelbësore mund të ndikojë funksionalitetin e platformës sonë, përfshirë hyrjen dhe veçoritë e rezervimit.',
    'cookies.section4.title': '4. Cookies e Palëve të Treta',
    'cookies.section4.content': 'Disa cookies në faqen tonë vendosen nga shërbime palësh të treta që ne përdorim, si ofruesit e analitikës (p.sh., Google Analytics) dhe platformat e mediave sociale (LinkedIn, Instagram). Këto palë të treta kanë politikat e tyre të privatësisë që rregullojnë si i përdorin të dhënat tuaja.',
    'cookies.section5.title': '5. Përditësimet e Kësaj Politike',
    'cookies.section5.content': 'Ne mund ta përditësojmë këtë Politikë Cookies herë pas here për të reflektuar ndryshimet në teknologji, legjislacion ose praktikat tona të biznesit. Çdo ndryshim do të postohet në këtë faqe me një datë rishikimi të përditësuar.',
    'cookies.contact.title': 'Na Kontaktoni',
    'cookies.contact.content': 'Nëse keni pyetje rreth përdorimit tonë të cookies, ju lutem na kontaktoni:',
    'cookies.contact.address': 'Rruga Dervish Shaba, Tiranë, Shqipëri, 1019',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
