import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'AL';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Navbar
    'nav.about': 'About',
    'nav.solutions': 'Solutions',
    'nav.connectivity': 'Connectivity',
    'nav.bedbank': 'Bedbank',
    'nav.global': 'Global',
    'nav.contact': 'Contact',
    'nav.partnerLogin': 'Partner Login',

    // Hero
    'hero.headline': 'Global B2B Travel Wholesaler',
    'hero.subheadline': '30+ years of trust, local strength, and unbeatable availability in the Western Balkans.',
    'hero.supportLine': 'Direct contracts. Instant booking. 24/7 support — built for travel agencies, OTAs, and wholesalers.',
    'hero.becomePartner': 'Become a Partner',
    'hero.readyToConnect': 'Ready to Connect?',

    // About
    'about.badge': 'ABOUT VASDREAM',
    'about.title': 'Built on Trust. Powered by Experience.',
    'about.description': 'Since 2015, VasDream has operated as a leading B2B travel wholesaler, backed by over 30 years of destination management expertise. Our deep-rooted relationships with hotels across the region make us the trusted choice for travel businesses worldwide.',
    'about.stat1.value': '2015',
    'about.stat1.label': 'Founded',
    'about.stat1.sublabel': 'B2B Operations',
    'about.stat2.value': '30+',
    'about.stat2.label': 'Years Experience',
    'about.stat2.sublabel': 'DMC Background',
    'about.stat3.value': '3M+',
    'about.stat3.label': 'Hotels',
    'about.stat3.sublabel': 'Worldwide Inventory',
    'about.stat4.value': '24/7',
    'about.stat4.label': 'Support',
    'about.stat4.sublabel': 'Multilingual Team',
    'about.feature1.title': 'Local Expertise',
    'about.feature1.description': 'In-market contracting teams across Albania, Montenegro, Greece, and the entire Balkan region.',
    'about.feature2.title': 'Trusted Relationships',
    'about.feature2.description': 'Long-standing partnerships with hotels who know and respect the VasDream name.',
    'about.feature3.title': 'Market Leadership',
    'about.feature3.description': 'Recognized as the go-to wholesaler for Western Balkans hotel inventory.',

    // Solutions
    'solutions.badge': 'OUR SOLUTIONS',
    'solutions.title': 'Everything You Need to Scale',
    'solutions.description': 'From direct hotel contracts to seamless API integration, we provide the tools and support travel businesses need to succeed.',
    'solutions.directContracting.title': 'Direct Contracting',
    'solutions.directContracting.description': 'Access 6,500+ direct hotel contracts with competitive rates negotiated by our local teams.',
    'solutions.extranetAccess.title': 'Extranet Access',
    'solutions.extranetAccess.description': 'User-friendly platform for real-time inventory management, booking, and reporting.',
    'solutions.apiIntegration.title': 'XML / API Integration',
    'solutions.apiIntegration.description': 'Seamless connectivity with your existing systems via XML or JSON APIs.',
    'solutions.exclusiveRates.title': 'Exclusive Rates',
    'solutions.exclusiveRates.description': 'Competitive pricing with strong margins, backed by our direct supplier relationships.',
    'solutions.support.title': '24/7 Multilingual Support',
    'solutions.support.description': 'Round-the-clock assistance in multiple languages from our dedicated team.',
    'solutions.advancedFilters.title': 'Advanced Filters',
    'solutions.advancedFilters.description': 'Search by destination, category, board type, and more to find the perfect properties.',
    'solutions.cta': 'Explore All Solutions',

    // Connectivity
    'connectivity.badge': 'CONNECTIVITY',
    'connectivity.title': 'Seamless Integration',
    'connectivity.description': 'Connect your systems to our extensive hotel network through industry-leading platforms and direct API access.',
    'connectivity.yourSystem': 'Your System',
    'connectivity.yourSystemDesc': 'Connect through major platforms or integrate directly with our API for full access to our hotel inventory.',
    'connectivity.vasdream': 'VasDream',
    'connectivity.vasdreamDesc': 'Unified API gateway with real-time availability and instant confirmation.',
    'connectivity.hotelInventory': 'Hotel Inventory',
    'connectivity.hotelInventoryDesc': 'Access our direct contracts across Albania, Montenegro, Greece & Balkan region.',
    'connectivity.connectedPlatforms': 'Connected Platforms',
    'connectivity.apiSpecs': 'API Specifications',
    'connectivity.xmlJson': 'XML & JSON',
    'connectivity.xmlJsonDesc': 'Flexible data formats',
    'connectivity.sslSecured': 'SSL Secured',
    'connectivity.sslSecuredDesc': 'Enterprise-grade security',
    'connectivity.uptime': '99.9% Uptime',
    'connectivity.uptimeDesc': 'Reliable infrastructure',

    // Bedbank
    'bedbank.badge': 'NEW FEATURE',
    'bedbank.title': 'VasDream Bedbank',
    'bedbank.subtitle': "Albania's Only Dedicated Bedbank",
    'bedbank.description': 'Leverage our 6,500+ direct hotel contracts through a modern distribution platform designed for serious travel businesses.',
    'bedbank.feature1': 'API & Extranet Distribution',
    'bedbank.feature2': 'Transparent Real-time Availability',
    'bedbank.feature3': 'Strong Margins & Competitive Rates',
    'bedbank.feature4': 'Perfect for OTAs, DMCs & Wholesalers',
    'bedbank.cta': 'Access Bedbank',
    'bedbank.hotelTitle': 'Are You a Hotel?',
    'bedbank.hotelDescription': "Join Albania's premier bedbank and expand your distribution reach. Our platform connects you with verified travel buyers worldwide.",
    'bedbank.hotelBenefit1': 'Global Distribution Network',
    'bedbank.hotelBenefit1Desc': 'Reach thousands of travel agencies, OTAs, and tour operators worldwide',
    'bedbank.hotelBenefit2': 'No Upfront Costs',
    'bedbank.hotelBenefit2Desc': 'Commission-based model with no setup or monthly fees',
    'bedbank.hotelBenefit3': 'Dedicated Account Manager',
    'bedbank.hotelBenefit3Desc': 'Personal support to optimize your rates and availability',
    'bedbank.hotelBenefit4': 'Real-time Connectivity',
    'bedbank.hotelBenefit4Desc': 'Seamless channel manager integration with instant updates',
    'bedbank.hotelCta': 'List Your Hotel',
    'bedbank.formTitle': 'Hotel Inquiry Form',
    'bedbank.formDescription': 'Fill out the form below and our hotel partnerships team will contact you within 24 hours.',
    'bedbank.formHotelName': 'Hotel Name',
    'bedbank.formContactName': 'Contact Name',
    'bedbank.formEmail': 'Email Address',
    'bedbank.formPhone': 'Phone Number',
    'bedbank.formLocation': 'Hotel Location',
    'bedbank.formRooms': 'Number of Rooms',
    'bedbank.formSubmit': 'Submit Inquiry',
    'bedbank.formCancel': 'Cancel',

    // Who We Serve
    'serve.badge': 'WHO WE SERVE',
    'serve.title': 'Built for Every Travel Business',
    'serve.description': 'Whether you\'re a boutique agency or a global OTA, VasDream provides the tools and inventory you need to succeed.',
    'serve.tab1': 'Travel Agencies',
    'serve.tab2': 'OTAs & Wholesalers',
    'serve.tab3': 'Corporate',
    'serve.tab4': 'Tech Integrators',
    'serve.agencies.title': 'For Travel Agencies',
    'serve.agencies.description': 'Empower your agency with competitive rates, dedicated support, and tools designed for your success.',
    'serve.agencies.feature1': 'Margin Control',
    'serve.agencies.feature1Desc': 'Full transparency on net rates with flexible markup options',
    'serve.agencies.feature2': 'Account Manager',
    'serve.agencies.feature2Desc': 'Dedicated support to help you grow your business',
    'serve.agencies.feature3': 'White-label Tools',
    'serve.agencies.feature3Desc': 'Brand the booking experience as your own',
    'serve.otas.title': 'For OTAs & Wholesalers',
    'serve.otas.description': 'Scale your business with volume access and seamless API connectivity.',
    'serve.otas.feature1': 'Volume Access',
    'serve.otas.feature1Desc': 'High-volume availability for peak demand periods',
    'serve.otas.feature2': 'API Connection',
    'serve.otas.feature2Desc': 'Direct XML/JSON integration with your platform',
    'serve.otas.feature3': 'Competitive Rates',
    'serve.otas.feature3Desc': 'Best-in-market pricing for maximum margins',
    'serve.corporate.title': 'For Corporate Clients',
    'serve.corporate.description': 'Streamline business travel with clean dashboards and negotiated rates.',
    'serve.corporate.feature1': 'Clean Dashboard',
    'serve.corporate.feature1Desc': 'Easy-to-use interface for booking management',
    'serve.corporate.feature2': 'Special Rates',
    'serve.corporate.feature2Desc': 'Negotiated corporate pricing programs',
    'serve.corporate.feature3': 'Reporting Tools',
    'serve.corporate.feature3Desc': 'Comprehensive travel spend analytics',
    'serve.tech.title': 'For Tech Integrators',
    'serve.tech.description': 'Build on our API-ready infrastructure designed for scale.',
    'serve.tech.feature1': 'API-Ready',
    'serve.tech.feature1Desc': 'Well-documented APIs for fast integration',
    'serve.tech.feature2': 'Scalable Design',
    'serve.tech.feature2Desc': 'Infrastructure built to handle growth',
    'serve.tech.feature3': 'Dev Support',
    'serve.tech.feature3Desc': 'Technical team available for integration assistance',

    // Global
    'global.badge': 'GLOBAL PRESENCE',
    'global.title': 'Offices Worldwide',
    'global.description': 'With strategic locations across Europe and the Middle East, we provide local expertise with global reach.',
    'global.headquarters': 'Headquarters',
    'global.office': 'Office',
    'global.trustedBy': 'Trusted by Industry Leaders',
    'global.andMore': 'and many more',

    // Testimonials
    'testimonials.badge': 'TESTIMONIALS',
    'testimonials.title': 'What Our Partners Say',

    // CTA
    'cta.title': 'Ready to Connect?',
    'cta.description': 'Join 1000+ partners who rely on VasDream for trusted hotel supply, with instant booking and unbeatable service.',
    'cta.feature1': 'No setup fees',
    'cta.feature2': '24/7 support',
    'cta.feature3': 'Multi-language support (EN / AL)',
    'cta.becomePartner': 'Become a Partner',
    'cta.explorePlatform': 'Explore Platform',

    // Footer
    'footer.description': 'Connecting travel businesses to 3M+ hotels across 190+ countries with cutting-edge API technology.',
    'footer.travelAgencies': 'Travel Agencies',
    'footer.otasDmcs': 'OTAs, DMCs, Tour Operators & Tech Platforms',
    'footer.company': 'Company',
    'footer.careers': 'Careers',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.cookiesPolicy': 'Cookies Policy',
    'footer.newsletter': 'Subscribe to Newsletter',
    'footer.emailPlaceholder': 'Enter your email',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved.',
    'footer.apiStatus': 'API Status: Operational',

    // Login Modal
    'login.title': 'Partner Login',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.forgotPassword': 'Forgot password?',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Register here',
  },
  AL: {
    // Navbar
    'nav.about': 'Rreth Nesh',
    'nav.solutions': 'Zgjidhjet',
    'nav.connectivity': 'Lidhja',
    'nav.bedbank': 'Bedbank',
    'nav.global': 'Global',
    'nav.contact': 'Kontakt',
    'nav.partnerLogin': 'Hyrje Partneri',

    // Hero
    'hero.headline': 'Shitës me Shumicë Global B2B për Udhëtime',
    'hero.subheadline': '30+ vjet besim, forcë lokale dhe disponueshmëri e paarritshme në Ballkanin Perëndimor.',
    'hero.supportLine': 'Kontrata direkte. Rezervim i menjëhershëm. Mbështetje 24/7 — ndërtuar për agjenci udhëtimi, OTA dhe shitës me shumicë.',
    'hero.becomePartner': 'Bëhu Partner',
    'hero.readyToConnect': 'Gati për t\'u Lidhur?',

    // About
    'about.badge': 'RRETH VASDREAM',
    'about.title': 'Ndërtuar mbi Besim. Mundësuar nga Përvoja.',
    'about.description': 'Që nga viti 2015, VasDream ka operuar si shitës kryesor me shumicë B2B për udhëtime, i mbështetur nga mbi 30 vjet ekspertizë në menaxhimin e destinacioneve. Marrëdhëniet tona të thella me hotelet në rajon na bëjnë zgjedhjen e besuar për bizneset e udhëtimit në mbarë botën.',
    'about.stat1.value': '2015',
    'about.stat1.label': 'Themeluar',
    'about.stat1.sublabel': 'Operacione B2B',
    'about.stat2.value': '30+',
    'about.stat2.label': 'Vjet Përvojë',
    'about.stat2.sublabel': 'Sfond DMC',
    'about.stat3.value': '3M+',
    'about.stat3.label': 'Hotele',
    'about.stat3.sublabel': 'Inventar Botëror',
    'about.stat4.value': '24/7',
    'about.stat4.label': 'Mbështetje',
    'about.stat4.sublabel': 'Ekip Shumëgjuhësh',
    'about.feature1.title': 'Ekspertizë Lokale',
    'about.feature1.description': 'Ekipe kontraktimi në treg në Shqipëri, Mal të Zi, Greqi dhe të gjithë rajonin e Ballkanit.',
    'about.feature2.title': 'Marrëdhënie të Besuara',
    'about.feature2.description': 'Partneritete afatgjata me hotele që njohin dhe respektojnë emrin VasDream.',
    'about.feature3.title': 'Lidershipi në Treg',
    'about.feature3.description': 'I njohur si shitësi kryesor me shumicë për inventarin e hoteleve të Ballkanit Perëndimor.',

    // Solutions
    'solutions.badge': 'ZGJIDHJET TONA',
    'solutions.title': 'Gjithçka që Ju Nevojitet për të Rritur',
    'solutions.description': 'Nga kontratat direkte të hoteleve tek integrimi i pandërprerë API, ne ofrojmë mjetet dhe mbështetjen që bizneset e udhëtimit kanë nevojë për të pasur sukses.',
    'solutions.directContracting.title': 'Kontraktim Direkt',
    'solutions.directContracting.description': 'Qasje në 6,500+ kontrata direkte hotelesh me çmime konkurruese të negociuara nga ekipet tona lokale.',
    'solutions.extranetAccess.title': 'Qasje Extranet',
    'solutions.extranetAccess.description': 'Platformë e lehtë për përdoruesin për menaxhimin e inventarit në kohë reale, rezervime dhe raportim.',
    'solutions.apiIntegration.title': 'Integrim XML / API',
    'solutions.apiIntegration.description': 'Lidhje e pandërprerë me sistemet tuaja ekzistuese përmes API-ve XML ose JSON.',
    'solutions.exclusiveRates.title': 'Çmime Ekskluzive',
    'solutions.exclusiveRates.description': 'Çmime konkurruese me marzhe të forta, të mbështetura nga marrëdhëniet tona direkte me furnitorët.',
    'solutions.support.title': 'Mbështetje 24/7 Shumëgjuhëshe',
    'solutions.support.description': 'Ndihmë gjatë gjithë kohës në shumë gjuhë nga ekipi ynë i dedikuar.',
    'solutions.advancedFilters.title': 'Filtra të Avancuara',
    'solutions.advancedFilters.description': 'Kërkoni sipas destinacionit, kategorisë, llojit të bordit dhe më shumë për të gjetur pronat e përsosura.',
    'solutions.cta': 'Eksploroni të Gjitha Zgjidhjet',

    // Connectivity
    'connectivity.badge': 'LIDHJA',
    'connectivity.title': 'Integrim i Pandërprerë',
    'connectivity.description': 'Lidhni sistemet tuaja me rrjetin tonë të gjerë të hoteleve përmes platformave kryesore të industrisë dhe qasjes direkte API.',
    'connectivity.yourSystem': 'Sistemi Juaj',
    'connectivity.yourSystemDesc': 'Lidhuni përmes platformave kryesore ose integrohuni direkt me API-në tonë për qasje të plotë në inventarin tonë të hoteleve.',
    'connectivity.vasdream': 'VasDream',
    'connectivity.vasdreamDesc': 'Portë API e unifikuar me disponueshmëri në kohë reale dhe konfirmim të menjëhershëm.',
    'connectivity.hotelInventory': 'Inventari i Hoteleve',
    'connectivity.hotelInventoryDesc': 'Qasje në kontratat tona direkte në Shqipëri, Mal të Zi, Greqi & rajonin e Ballkanit.',
    'connectivity.connectedPlatforms': 'Platformat e Lidhura',
    'connectivity.apiSpecs': 'Specifikimet API',
    'connectivity.xmlJson': 'XML & JSON',
    'connectivity.xmlJsonDesc': 'Formate fleksibël të dhënash',
    'connectivity.sslSecured': 'I Siguruar me SSL',
    'connectivity.sslSecuredDesc': 'Siguri e nivelit enterprise',
    'connectivity.uptime': '99.9% Kohë Funksionimi',
    'connectivity.uptimeDesc': 'Infrastrukturë e besueshme',

    // Bedbank
    'bedbank.badge': 'VEÇORI E RE',
    'bedbank.title': 'VasDream Bedbank',
    'bedbank.subtitle': 'I Vetmi Bedbank i Dedikuar në Shqipëri',
    'bedbank.description': 'Shfrytëzoni 6,500+ kontratat tona direkte të hoteleve përmes një platforme moderne shpërndarjeje të dizajnuar për biznese serioze të udhëtimit.',
    'bedbank.feature1': 'Shpërndarje API & Extranet',
    'bedbank.feature2': 'Disponueshmëri Transparente në Kohë Reale',
    'bedbank.feature3': 'Marzhe të Forta & Çmime Konkurruese',
    'bedbank.feature4': 'Perfekt për OTA, DMC & Shitës me Shumicë',
    'bedbank.cta': 'Qasje në Bedbank',
    'bedbank.hotelTitle': 'Jeni Hotel?',
    'bedbank.hotelDescription': 'Bashkohuni me bedbank-un kryesor të Shqipërisë dhe zgjeroni shtrirjen tuaj të shpërndarjes. Platforma jonë ju lidh me blerës të verifikuar udhëtimi në mbarë botën.',
    'bedbank.hotelBenefit1': 'Rrjet Global Shpërndarjeje',
    'bedbank.hotelBenefit1Desc': 'Arrini mijëra agjenci udhëtimi, OTA dhe operatorë turne në mbarë botën',
    'bedbank.hotelBenefit2': 'Pa Kosto Paraprake',
    'bedbank.hotelBenefit2Desc': 'Model i bazuar në komision pa tarifa vendosjeje ose mujore',
    'bedbank.hotelBenefit3': 'Menaxher Llogarie i Dedikuar',
    'bedbank.hotelBenefit3Desc': 'Mbështetje personale për të optimizuar çmimet dhe disponueshmërinë tuaj',
    'bedbank.hotelBenefit4': 'Lidhje në Kohë Reale',
    'bedbank.hotelBenefit4Desc': 'Integrim i pandërprerë i menaxherit të kanalit me përditësime të menjëhershme',
    'bedbank.hotelCta': 'Listoni Hotelin Tuaj',
    'bedbank.formTitle': 'Formular Pyetjeje për Hotel',
    'bedbank.formDescription': 'Plotësoni formularin më poshtë dhe ekipi ynë i partneriteteve hoteliere do t\'ju kontaktojë brenda 24 orëve.',
    'bedbank.formHotelName': 'Emri i Hotelit',
    'bedbank.formContactName': 'Emri i Kontaktit',
    'bedbank.formEmail': 'Adresa Email',
    'bedbank.formPhone': 'Numri i Telefonit',
    'bedbank.formLocation': 'Vendndodhja e Hotelit',
    'bedbank.formRooms': 'Numri i Dhomave',
    'bedbank.formSubmit': 'Dërgo Pyetjen',
    'bedbank.formCancel': 'Anulo',

    // Who We Serve
    'serve.badge': 'KUSH SHËRBEJMË',
    'serve.title': 'Ndërtuar për Çdo Biznes Udhëtimi',
    'serve.description': 'Pavarësisht nëse jeni një agjenci butike ose një OTA global, VasDream ofron mjetet dhe inventarin që ju nevojitet për të pasur sukses.',
    'serve.tab1': 'Agjenci Udhëtimi',
    'serve.tab2': 'OTA & Shitës me Shumicë',
    'serve.tab3': 'Korporata',
    'serve.tab4': 'Integrues Teknologjikë',
    'serve.agencies.title': 'Për Agjencinë e Udhëtimit',
    'serve.agencies.description': 'Fuqizoni agjencininë tuaj me çmime konkurruese, mbështetje të dedikuar dhe mjete të dizajnuara për suksesin tuaj.',
    'serve.agencies.feature1': 'Kontroll Marzhi',
    'serve.agencies.feature1Desc': 'Transparencë e plotë në çmimet neto me opsione fleksibël të rritjes',
    'serve.agencies.feature2': 'Menaxher Llogarie',
    'serve.agencies.feature2Desc': 'Mbështetje e dedikuar për t\'ju ndihmuar të rrisni biznesin tuaj',
    'serve.agencies.feature3': 'Mjete White-label',
    'serve.agencies.feature3Desc': 'Personalizoni përvojën e rezervimit si tuajën',
    'serve.otas.title': 'Për OTA & Shitës me Shumicë',
    'serve.otas.description': 'Zgjeroni biznesin tuaj me qasje në vëllim dhe lidhje API të pandërprerë.',
    'serve.otas.feature1': 'Qasje në Vëllim',
    'serve.otas.feature1Desc': 'Disponueshmëri me vëllim të lartë për periudhat e kërkesës së lartë',
    'serve.otas.feature2': 'Lidhje API',
    'serve.otas.feature2Desc': 'Integrim direkt XML/JSON me platformën tuaj',
    'serve.otas.feature3': 'Çmime Konkurruese',
    'serve.otas.feature3Desc': 'Çmimet më të mira në treg për marzhe maksimale',
    'serve.corporate.title': 'Për Klientë Korporativë',
    'serve.corporate.description': 'Thjeshtoni udhëtimet e biznesit me panele të pastra dhe çmime të negociuara.',
    'serve.corporate.feature1': 'Panel i Pastër',
    'serve.corporate.feature1Desc': 'Ndërfaqe e lehtë për përdorim për menaxhimin e rezervimeve',
    'serve.corporate.feature2': 'Çmime Speciale',
    'serve.corporate.feature2Desc': 'Programe çmimesh korporative të negociuara',
    'serve.corporate.feature3': 'Mjete Raportimi',
    'serve.corporate.feature3Desc': 'Analitika gjithëpërfshirëse të shpenzimeve të udhëtimit',
    'serve.tech.title': 'Për Integrues Teknologjikë',
    'serve.tech.description': 'Ndërtoni mbi infrastrukturën tonë të gatshme për API të dizajnuar për shkallëzim.',
    'serve.tech.feature1': 'I Gatshëm për API',
    'serve.tech.feature1Desc': 'API të dokumentuara mirë për integrim të shpejtë',
    'serve.tech.feature2': 'Dizajn i Shkallëzueshëm',
    'serve.tech.feature2Desc': 'Infrastrukturë e ndërtuar për të trajtuar rritjen',
    'serve.tech.feature3': 'Mbështetje Dev',
    'serve.tech.feature3Desc': 'Ekip teknik i disponueshëm për ndihmë integrimi',

    // Global
    'global.badge': 'PREZENCË GLOBALE',
    'global.title': 'Zyra në Mbarë Botën',
    'global.description': 'Me vendndodhje strategjike në Europë dhe Lindjen e Mesme, ne ofrojmë ekspertizë lokale me shtrirje globale.',
    'global.headquarters': 'Selia Qendrore',
    'global.office': 'Zyrë',
    'global.trustedBy': 'I Besuar nga Liderët e Industrisë',
    'global.andMore': 'dhe shumë të tjera',

    // Testimonials
    'testimonials.badge': 'DËSHMITË',
    'testimonials.title': 'Çfarë Thonë Partnerët Tanë',

    // CTA
    'cta.title': 'Gati për t\'u Lidhur?',
    'cta.description': 'Bashkohuni me 1000+ partnerë që mbështeten tek VasDream për furnizim të besuar hotelesh, me rezervim të menjëhershëm dhe shërbim të paarritshëm.',
    'cta.feature1': 'Pa tarifa vendosjeje',
    'cta.feature2': 'Mbështetje 24/7',
    'cta.feature3': 'Mbështetje shumëgjuhëshe (EN / AL)',
    'cta.becomePartner': 'Bëhu Partner',
    'cta.explorePlatform': 'Eksploroni Platformën',

    // Footer
    'footer.description': 'Duke lidhur bizneset e udhëtimit me 3M+ hotele në 190+ vende me teknologji API të avancuar.',
    'footer.travelAgencies': 'Agjenci Udhëtimi',
    'footer.otasDmcs': 'OTA, DMC, Operatorë Turne & Platforma Teknologjike',
    'footer.company': 'Kompania',
    'footer.careers': 'Karriera',
    'footer.contact': 'Kontakt',
    'footer.legal': 'Ligjore',
    'footer.privacyPolicy': 'Politika e Privatësisë',
    'footer.cookiesPolicy': 'Politika e Cookies',
    'footer.newsletter': 'Abonohu në Newsletter',
    'footer.emailPlaceholder': 'Shkruani email-in tuaj',
    'footer.subscribe': 'Abonohu',
    'footer.rights': 'Të gjitha të drejtat e rezervuara.',
    'footer.apiStatus': 'Statusi API: Operacional',

    // Login Modal
    'login.title': 'Hyrje Partneri',
    'login.email': 'Email',
    'login.password': 'Fjalëkalimi',
    'login.submit': 'Hyr',
    'login.forgotPassword': 'Keni harruar fjalëkalimin?',
    'login.noAccount': 'Nuk keni llogari?',
    'login.register': 'Regjistrohuni këtu',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
