import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'AL';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Navbar
    'nav.about': 'About',
    'nav.solutions': 'Solutions',
    'nav.connectivity': 'Connectivity',
    'nav.bedbank': 'Bedbank',
    'nav.global': 'Global',
    'nav.contact': 'Contact',
    'nav.partnerLogin': 'Partner Login',

    // Hero
    'hero.headline': 'Global B2B Travel Wholesaler',
    'hero.subheadline': '30+ years of trust, local strength, and unbeatable availability in the Western Balkans.',
    'hero.experience': 'Since 2015, 30+ Years Travel Group Experience',
    'hero.features': 'Direct contracts • Instant booking • 24/7 support',
    'hero.builtFor': 'Built for Travel Agencies, OTAs and DMCs.',
    'hero.becomePartner': 'Become a Partner',
    'hero.readyToConnect': 'Ready to Connect?',

    // About
    'about.badge': 'OUR STORY',
    'about.title1': "Albania's Leading",
    'about.title2': 'B2B Travel Wholesaler',
    'about.description1': 'VasDream has been a cornerstone of the Western Balkans travel industry since 2015, building on over',
    'about.description1Highlight': '30 years of travel experience',
    'about.description2': 'With Global Inventory across the entire globe, we\'ve established ourselves as the region\'s most trusted B2B wholesaler.',
    'about.description2Highlight': 'Worldwide Inventory',
    'about.description2Rest': 'across Albania, Montenegro, Greece, and the wider Balkan Peninsula, we\'ve established ourselves as the region\'s most trusted B2B wholesaler.',
    'about.description3': 'Our strength lies in our local presence — dedicated support teams, long-standing travel partner relationships, and unmatched regional knowledge that gives our clients access to inventory and rates unavailable elsewhere.',
    'about.stat1': '3M+ Hotels',
    'about.stat2': 'Dedicated 24/7 Support',
    'about.highlight1.title': 'Since 2015',
    'about.highlight1.desc': 'Operating as a dedicated B2B wholesaler',
    'about.highlight2.title': '30+ Years Experience',
    'about.highlight2.desc': 'Backed by destination management expertise',
    'about.highlight3.title': '3M+ Hotels',
    'about.highlight3.desc': 'Worldwide Inventory and availability',
    'about.highlight4.title': 'Known & Respected',
    'about.highlight4.desc': 'Trusted by hotels, respected in-market',
    'about.highlight5.title': 'Local Teams',
    'about.highlight5.desc': 'Dedicated contracting teams on the ground',
    'about.highlight6.title': 'Long-term Relationships',
    'about.highlight6.desc': 'Decades of supplier partnerships',

    // Solutions
    'solutions.badge': 'OUR SOLUTIONS',
    'solutions.title': 'Our Solutions',
    'solutions.description': 'Everything you need to power your travel business with the Western Balkans\' premier hotel inventory',
    'solutions.globalInventory.title': 'Global Inventory',
    'solutions.globalInventory.description': 'Access 3M+ hotels worldwide through our integrated network of global suppliers and direct contracts.',
    'solutions.extranetAccess.title': 'Extranet Access',
    'solutions.extranetAccess.description': 'Manage bookings, view availability, and control inventory through our intuitive platform.',
    'solutions.apiIntegration.title': 'XML / API Integration',
    'solutions.apiIntegration.description': 'Seamless technical integration with your existing systems via XML or JSON API.',
    'solutions.exclusiveRates.title': 'Exclusive Rates',
    'solutions.exclusiveRates.description': 'Preferential pricing unavailable on public channels, maximizing your margins.',
    'solutions.support.title': '24/7 Multilingual Support',
    'solutions.support.description': 'Round-the-clock assistance in multiple languages whenever you need it.',
    'solutions.advancedFilters.title': 'Advanced Filtering',
    'solutions.advancedFilters.description': 'Search and filter by destination, category, board type, and more.',
    'solutions.serving': 'Serving Travel Professionals Worldwide',
    'solutions.otas': 'OTAs',
    'solutions.dmcs': 'DMCs',
    'solutions.agencies': 'Agencies',
    'solutions.corporate': 'Corporate',

    // Connectivity
    'connectivity.title': 'Seamless Integration Ecosystem',
    'connectivity.description': 'Connect your systems to the world\'s leading travel technology platforms',
    'connectivity.yourSystem': 'Your System',
    'connectivity.yourSystemDesc': 'All major platforms connected with multiple integration methods',
    'connectivity.vasdream': 'VasDream',
    'connectivity.apiGateway': 'API Gateway',
    'connectivity.hotelInventory': 'Hotel Inventory',
    'connectivity.hotelsWorldwide': '3M+ Hotels Worldwide',
    'connectivity.connectedPlatforms': 'Connected Platforms',
    'connectivity.xmlJsonApi': 'XML & JSON API',
    'connectivity.uptimeSla': '99.9% Uptime SLA',
    'connectivity.sslSecured': 'SSL Secured',

    // Bedbank
    'bedbank.badge': 'NOW LIVE',
    'bedbank.badgeText': 'New Feature',
    'bedbank.title': 'VasDream Bedbank',
    'bedbank.subtitle': 'The only dedicated bedbank in Albania — powered by our exclusive portfolio of',
    'bedbank.subtitleHighlight': '6,500+ directly contracted hotels',
    'bedbank.description': 'Whether you\'re an OTA scaling your Balkan inventory, a DMC seeking reliable supply, or a regional wholesaler expanding your reach, VasDream Bedbank delivers transparent availability and strong margins through API or Extranet.',
    'bedbank.getStarted': 'Get Started',
    'bedbank.availableVia': 'Available via API & Extranet',
    'bedbank.feature1.title': '6,500+ Direct Contracts',
    'bedbank.feature1.desc': 'Albania, Montenegro, Greece & the Balkans — all directly contracted.',
    'bedbank.feature2.title': 'Transparent Availability',
    'bedbank.feature2.desc': 'Real-time rates and inventory with strong margins for your business.',
    'bedbank.feature3.title': 'Distribution Flexibility',
    'bedbank.feature3.desc': 'Access via API integration or through our intuitive Extranet platform.',
    'bedbank.feature4.title': 'Perfect For Your Business',
    'bedbank.feature4.desc': 'Ideal for OTAs, DMCs, and regional wholesalers seeking quality inventory.',
    'bedbank.hotelTitle': 'Are you a hotel?',
    'bedbank.hotelDesc': 'Join our distribution network and unlock access to a global network of travel buyers. List your property with VasDream Bedbank and benefit from:',
    'bedbank.hotelBenefit1': 'Global distribution to 1000+ B2B partners worldwide',
    'bedbank.hotelBenefit2': 'Access to travel agencies, OTAs, and tour operators',
    'bedbank.hotelBenefit3': 'Competitive commission structures with transparent pricing',
    'bedbank.hotelBenefit4': 'Dedicated account management and 24/7 support',
    'bedbank.startHere': 'Start Here',
    'bedbank.formTitle': 'List Your Hotel',
    'bedbank.formDesc': 'Fill in your details and our representatives will contact you within 24 hours to discuss partnership opportunities.',
    'bedbank.formHotelName': 'Hotel Name',
    'bedbank.formContactName': 'Contact Name',
    'bedbank.formEmail': 'Email',
    'bedbank.formPhone': 'Phone',
    'bedbank.formLocation': 'Location',
    'bedbank.formRooms': 'Number of Rooms',
    'bedbank.formSubmit': 'Submit Request',

    // Who We Serve
    'serve.title': 'Who We Serve',
    'serve.description': 'Tailored solutions for every travel business model',
    'serve.agencies': 'Travel Agencies',
    'serve.otas': 'OTAs & Wholesalers',
    'serve.corporate': 'Corporate',
    'serve.tech': 'Tech Integrators',
    'serve.agencies.title': 'Full margin control with dedicated support',
    'serve.agencies.desc': 'Access competitive B2B rates with transparent pricing that lets you maintain healthy margins. Every agency partner gets a dedicated account manager who understands your business.',
    'serve.agencies.feature1': 'Margin control tools',
    'serve.agencies.feature2': 'Dedicated account manager',
    'serve.agencies.feature3': 'White-label booking solutions',
    'serve.agencies.feature4': 'Competitive B2B rates',
    'serve.otas.title': 'Volume access with seamless API connection',
    'serve.otas.desc': 'Built for high-volume operations with robust API infrastructure. Scale your Balkan inventory without infrastructure concerns — our platform handles thousands of requests effortlessly.',
    'serve.otas.feature1': 'High-volume API access',
    'serve.otas.feature2': 'Bulk rate management',
    'serve.otas.feature3': 'Real-time availability',
    'serve.otas.feature4': 'Automated booking flow',
    'serve.corporate.title': 'Clean dashboard with special corporate rates',
    'serve.corporate.desc': 'Streamline business travel with our corporate booking platform. Access negotiated rates, manage policies, and get detailed reporting for finance teams.',
    'serve.corporate.feature1': 'Corporate rate programs',
    'serve.corporate.feature2': 'Clean booking dashboard',
    'serve.corporate.feature3': 'Policy management',
    'serve.corporate.feature4': 'Travel expense reporting',
    'serve.tech.title': 'API-ready with scalable architecture',
    'serve.tech.desc': 'Developer-first approach with comprehensive documentation and a scalable design that grows with your platform. XML and JSON support for maximum flexibility.',
    'serve.tech.feature1': 'RESTful & SOAP APIs',
    'serve.tech.feature2': 'Comprehensive documentation',
    'serve.tech.feature3': 'Scalable architecture',
    'serve.tech.feature4': '24/7 technical support',

    // Global
    'global.badge': 'GLOBAL PRESENCE',
    'global.title': 'Offices Worldwide',
    'global.description': 'With strategic locations across Europe and the Middle East, we provide local expertise with global reach.',
    'global.headquarters': 'Headquarters',
    'global.office': 'Office',
    'global.trustedBy': 'Trusted by Industry Leaders',
    'global.andMore': 'and many more',

    // Testimonials
    'testimonials.title': 'What Partners Say',

    // CTA
    'cta.title': 'Ready to Connect?',
    'cta.description': 'Join 1000+ partners who rely on VasDream for trusted hotel supply, with instant booking and unbeatable service.',
    'cta.feature1': 'No setup fees',
    'cta.feature2': '24/7 support',
    'cta.feature3': 'Multi-language support (EN / AL)',
    'cta.becomePartner': 'Become a Partner',
    'cta.explorePlatform': 'Explore Platform',

    // Footer
    'footer.description': 'Connecting travel businesses to 3M+ hotels across 190+ countries with cutting-edge API technology.',
    'footer.travelAgencies': 'Travel Agencies',
    'footer.otasDmcs': 'OTAs, DMCs, Tour Operators & Tech Platforms',
    'footer.company': 'Company',
    'footer.careers': 'Careers',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.cookiesPolicy': 'Cookies Policy',
    'footer.newsletter': 'Subscribe to Newsletter',
    'footer.newsletterDesc': 'Stay updated with the latest news and offers.',
    'footer.emailPlaceholder': 'Enter your email',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved.',
    'footer.apiStatus': 'API Status: Operational',

    // Partner Modal
    'partner.title': 'Become a Partner',
    'partner.subtitle': 'Choose how you want to connect with VasDream',
    'partner.agencyTitle': 'Travel Agency',
    'partner.agencyDesc': 'Get access to our booking platform with exclusive B2B rates and dedicated support.',
    'partner.apiTitle': 'API Integration',
    'partner.apiDesc': 'Connect your systems directly via XML or JSON API for automated booking flow.',
    'partner.back': 'Back to selection',
    'partner.companyName': 'Company Name',
    'partner.contactName': 'Contact Name',
    'partner.email': 'Email',
    'partner.phone': 'Phone',
    'partner.website': 'Website',
    'partner.message': 'Message (Optional)',
    'partner.submit': 'Submit Request',

    // Login Modal
    'login.title': 'Partner Login',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.forgotPassword': 'Forgot password?',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Register here',
  },
  AL: {
    // Navbar
    'nav.about': 'Rreth Nesh',
    'nav.solutions': 'Zgjidhjet',
    'nav.connectivity': 'Lidhja',
    'nav.bedbank': 'Bedbank',
    'nav.global': 'Global',
    'nav.contact': 'Kontakt',
    'nav.partnerLogin': 'Hyrje Partneri',

    // Hero
    'hero.headline': 'Shitës me Shumicë Global B2B për Udhëtime',
    'hero.subheadline': '30+ vjet besim, forcë lokale dhe disponueshmëri e paarritshme në Ballkanin Perëndimor.',
    'hero.experience': 'Që nga 2015, 30+ Vjet Përvojë në Grupin e Udhëtimeve',
    'hero.features': 'Kontrata direkte • Rezervim i menjëhershëm • Mbështetje 24/7',
    'hero.builtFor': 'Ndërtuar për Agjenci Udhëtimi, OTA dhe DMC.',
    'hero.becomePartner': 'Bëhu Partner',
    'hero.readyToConnect': 'Gati për t\'u Lidhur?',

    // About
    'about.badge': 'HISTORIA JONË',
    'about.title1': 'Shitësi Kryesor i Shqipërisë',
    'about.title2': 'B2B për Udhëtime me Shumicë',
    'about.description1': 'VasDream ka qenë gur themeli i industrisë së udhëtimeve në Ballkanin Perëndimor që nga 2015, duke u ndërtuar mbi',
    'about.description1Highlight': '30 vjet përvojë udhëtimi',
    'about.description2': 'Me Inventar Global në të gjithë globin, ne jemi vendosur si shitësi me shumicë më i besuar i rajonit.',
    'about.description2Highlight': 'Inventar Botëror',
    'about.description2Rest': 'në Shqipëri, Mal të Zi, Greqi dhe Gadishullin e gjerë Ballkanik, ne jemi vendosur si shitësi me shumicë më i besuar i rajonit.',
    'about.description3': 'Forca jonë qëndron në praninë tonë lokale — ekipe mbështetjeje të dedikuara, marrëdhënie afatgjata me partnerët e udhëtimit, dhe njohuri rajonale të pashoqe që u jep klientëve tanë qasje në inventar dhe çmime të padisponueshme gjetkë.',
    'about.stat1': '3M+ Hotele',
    'about.stat2': 'Mbështetje e Dedikuar 24/7',
    'about.highlight1.title': 'Që nga 2015',
    'about.highlight1.desc': 'Operim si shitës i dedikuar B2B me shumicë',
    'about.highlight2.title': '30+ Vjet Përvojë',
    'about.highlight2.desc': 'I mbështetur nga ekspertiza e menaxhimit të destinacionit',
    'about.highlight3.title': '3M+ Hotele',
    'about.highlight3.desc': 'Inventar dhe disponueshmëri botërore',
    'about.highlight4.title': 'I Njohur & I Respektuar',
    'about.highlight4.desc': 'I besuar nga hotelet, i respektuar në treg',
    'about.highlight5.title': 'Ekipe Lokale',
    'about.highlight5.desc': 'Ekipe kontraktimi të dedikuara në terren',
    'about.highlight6.title': 'Marrëdhënie Afatgjata',
    'about.highlight6.desc': 'Dekada partneritetesh me furnitorët',

    // Solutions
    'solutions.badge': 'ZGJIDHJET TONA',
    'solutions.title': 'Zgjidhjet Tona',
    'solutions.description': 'Gjithçka që ju nevojitet për të fuqizuar biznesin tuaj të udhëtimit me inventarin kryesor të hoteleve të Ballkanit Perëndimor',
    'solutions.globalInventory.title': 'Inventar Global',
    'solutions.globalInventory.description': 'Qasje në 3M+ hotele në mbarë botën përmes rrjetit tonë të integruar të furnitorëve globalë dhe kontratave direkte.',
    'solutions.extranetAccess.title': 'Qasje Extranet',
    'solutions.extranetAccess.description': 'Menaxhoni rezervimet, shikoni disponueshmërinë dhe kontrolloni inventarin përmes platformës sonë intuitive.',
    'solutions.apiIntegration.title': 'Integrim XML / API',
    'solutions.apiIntegration.description': 'Integrim teknik i pandërprerë me sistemet tuaja ekzistuese përmes XML ose JSON API.',
    'solutions.exclusiveRates.title': 'Çmime Ekskluzive',
    'solutions.exclusiveRates.description': 'Çmime preferenciale të padisponueshme në kanalet publike, duke maksimizuar marzhet tuaja.',
    'solutions.support.title': 'Mbështetje 24/7 Shumëgjuhëshe',
    'solutions.support.description': 'Ndihmë gjatë gjithë kohës në shumë gjuhë kur ju nevojitet.',
    'solutions.advancedFilters.title': 'Filtrim i Avancuar',
    'solutions.advancedFilters.description': 'Kërkoni dhe filtroni sipas destinacionit, kategorisë, llojit të bordit dhe më shumë.',
    'solutions.serving': 'Duke Shërbyer Profesionistët e Udhëtimit në Mbarë Botën',
    'solutions.otas': 'OTA',
    'solutions.dmcs': 'DMC',
    'solutions.agencies': 'Agjenci',
    'solutions.corporate': 'Korporata',

    // Connectivity
    'connectivity.title': 'Ekosistem Integrimi i Pandërprerë',
    'connectivity.description': 'Lidhni sistemet tuaja me platformat kryesore teknologjike të udhëtimit në botë',
    'connectivity.yourSystem': 'Sistemi Juaj',
    'connectivity.yourSystemDesc': 'Të gjitha platformat kryesore të lidhura me metoda të shumta integrimi',
    'connectivity.vasdream': 'VasDream',
    'connectivity.apiGateway': 'Porta API',
    'connectivity.hotelInventory': 'Inventari i Hoteleve',
    'connectivity.hotelsWorldwide': '3M+ Hotele në Mbarë Botën',
    'connectivity.connectedPlatforms': 'Platformat e Lidhura',
    'connectivity.xmlJsonApi': 'XML & JSON API',
    'connectivity.uptimeSla': '99.9% SLA Kohë Funksionimi',
    'connectivity.sslSecured': 'I Siguruar me SSL',

    // Bedbank
    'bedbank.badge': 'TANI LIVE',
    'bedbank.badgeText': 'Veçori e Re',
    'bedbank.title': 'VasDream Bedbank',
    'bedbank.subtitle': 'I vetmi bedbank i dedikuar në Shqipëri — i fuqizuar nga portofoli ynë ekskluziv i',
    'bedbank.subtitleHighlight': '6,500+ hoteleve të kontraktuara direkt',
    'bedbank.description': 'Qoftë jeni OTA që zgjeroni inventarin tuaj Ballkanik, DMC që kërkoni furnizim të besueshëm, ose shitës rajonal me shumicë që zgjeroni shtrirjen tuaj, VasDream Bedbank ofron disponueshmëri transparente dhe marzhe të forta përmes API ose Extranet.',
    'bedbank.getStarted': 'Filloni',
    'bedbank.availableVia': 'I disponueshëm përmes API & Extranet',
    'bedbank.feature1.title': '6,500+ Kontrata Direkte',
    'bedbank.feature1.desc': 'Shqipëri, Mal i Zi, Greqi & Ballkani — të gjitha të kontraktuara direkt.',
    'bedbank.feature2.title': 'Disponueshmëri Transparente',
    'bedbank.feature2.desc': 'Çmime dhe inventar në kohë reale me marzhe të forta për biznesin tuaj.',
    'bedbank.feature3.title': 'Fleksibilitet Shpërndarjeje',
    'bedbank.feature3.desc': 'Qasje përmes integrimit API ose përmes platformës sonë intuitive Extranet.',
    'bedbank.feature4.title': 'Perfekt Për Biznesin Tuaj',
    'bedbank.feature4.desc': 'Ideal për OTA, DMC dhe shitës rajonalë me shumicë që kërkojnë inventar cilësor.',
    'bedbank.hotelTitle': 'Jeni hotel?',
    'bedbank.hotelDesc': 'Bashkohuni me rrjetin tonë të shpërndarjes dhe zhbllokoni qasjen në një rrjet global blerësish udhëtimi. Listoni pronën tuaj me VasDream Bedbank dhe përfitoni nga:',
    'bedbank.hotelBenefit1': 'Shpërndarje globale te 1000+ partnerë B2B në mbarë botën',
    'bedbank.hotelBenefit2': 'Qasje në agjenci udhëtimi, OTA dhe operatorë turne',
    'bedbank.hotelBenefit3': 'Struktura komisioni konkurruese me çmime transparente',
    'bedbank.hotelBenefit4': 'Menaxhim i dedikuar i llogarisë dhe mbështetje 24/7',
    'bedbank.startHere': 'Filloni Këtu',
    'bedbank.formTitle': 'Listoni Hotelin Tuaj',
    'bedbank.formDesc': 'Plotësoni detajet tuaja dhe përfaqësuesit tanë do t\'ju kontaktojnë brenda 24 orëve për të diskutuar mundësitë e partneritetit.',
    'bedbank.formHotelName': 'Emri i Hotelit',
    'bedbank.formContactName': 'Emri i Kontaktit',
    'bedbank.formEmail': 'Email',
    'bedbank.formPhone': 'Telefon',
    'bedbank.formLocation': 'Vendndodhja',
    'bedbank.formRooms': 'Numri i Dhomave',
    'bedbank.formSubmit': 'Dorëzoni Kërkesën',

    // Who We Serve
    'serve.title': 'Kujt i Shërbejmë',
    'serve.description': 'Zgjidhje të personalizuara për çdo model biznesi udhëtimi',
    'serve.agencies': 'Agjenci Udhëtimi',
    'serve.otas': 'OTA & Shitës me Shumicë',
    'serve.corporate': 'Korporata',
    'serve.tech': 'Integrues Teknologjikë',
    'serve.agencies.title': 'Kontroll i plotë i marzheve me mbështetje të dedikuar',
    'serve.agencies.desc': 'Qasje në çmime konkurruese B2B me çmime transparente që ju lejojnë të mbani marzhe të shëndetshme. Çdo partner agjenci merr një menaxher llogarie të dedikuar që kupton biznesin tuaj.',
    'serve.agencies.feature1': 'Mjete kontrolli marzhesh',
    'serve.agencies.feature2': 'Menaxher llogarie i dedikuar',
    'serve.agencies.feature3': 'Zgjidhje rezervimi white-label',
    'serve.agencies.feature4': 'Çmime konkurruese B2B',
    'serve.otas.title': 'Qasje në vëllim me lidhje API të pandërprerë',
    'serve.otas.desc': 'Ndërtuar për operacione me vëllim të lartë me infrastrukturë API të fuqishme. Zgjeroni inventarin tuaj Ballkanik pa shqetësime infrastrukture — platforma jonë trajton mijëra kërkesa pa mundim.',
    'serve.otas.feature1': 'Qasje API me vëllim të lartë',
    'serve.otas.feature2': 'Menaxhim i çmimeve në masë',
    'serve.otas.feature3': 'Disponueshmëri në kohë reale',
    'serve.otas.feature4': 'Rrjedhë rezervimi e automatizuar',
    'serve.corporate.title': 'Panel i pastër me çmime speciale korporative',
    'serve.corporate.desc': 'Thjeshtësoni udhëtimet e biznesit me platformën tonë të rezervimeve korporative. Qasje në çmime të negociuara, menaxhoni politikat dhe merrni raportim të detajuar për ekipet financiare.',
    'serve.corporate.feature1': 'Programe çmimesh korporative',
    'serve.corporate.feature2': 'Panel rezervimi i pastër',
    'serve.corporate.feature3': 'Menaxhim politikash',
    'serve.corporate.feature4': 'Raportim shpenzimesh udhëtimi',
    'serve.tech.title': 'I gatshëm për API me arkitekturë të shkallëzueshme',
    'serve.tech.desc': 'Qasje developer-first me dokumentacion gjithëpërfshirës dhe dizajn të shkallëzueshëm që rritet me platformën tuaj. Mbështetje XML dhe JSON për fleksibilitet maksimal.',
    'serve.tech.feature1': 'API RESTful & SOAP',
    'serve.tech.feature2': 'Dokumentacion gjithëpërfshirës',
    'serve.tech.feature3': 'Arkitekturë e shkallëzueshme',
    'serve.tech.feature4': 'Mbështetje teknike 24/7',

    // Global
    'global.badge': 'PREZENCË GLOBALE',
    'global.title': 'Zyra në Mbarë Botën',
    'global.description': 'Me vendndodhje strategjike në Evropë dhe Lindjen e Mesme, ne ofrojmë ekspertizë lokale me shtrirje globale.',
    'global.headquarters': 'Seli Qendrore',
    'global.office': 'Zyrë',
    'global.trustedBy': 'Të Besuar nga Liderët e Industrisë',
    'global.andMore': 'dhe shumë të tjerë',

    // Testimonials
    'testimonials.title': 'Çfarë Thonë Partnerët',

    // CTA
    'cta.title': 'Gati për t\'u Lidhur?',
    'cta.description': 'Bashkohuni me 1000+ partnerë që mbështeten te VasDream për furnizim të besuar hotelesh, me rezervim të menjëhershëm dhe shërbim të paarritshëm.',
    'cta.feature1': 'Pa tarifa vendosjeje',
    'cta.feature2': 'Mbështetje 24/7',
    'cta.feature3': 'Mbështetje shumëgjuhëshe (EN / AL)',
    'cta.becomePartner': 'Bëhu Partner',
    'cta.explorePlatform': 'Eksploroni Platformën',

    // Footer
    'footer.description': 'Duke lidhur bizneset e udhëtimit me 3M+ hotele në 190+ vende me teknologji API të avancuar.',
    'footer.travelAgencies': 'Agjenci Udhëtimi',
    'footer.otasDmcs': 'OTA, DMC, Operatorë Turne & Platforma Teknologjike',
    'footer.company': 'Kompania',
    'footer.careers': 'Karriera',
    'footer.contact': 'Kontakt',
    'footer.legal': 'Ligjore',
    'footer.privacyPolicy': 'Politika e Privatësisë',
    'footer.cookiesPolicy': 'Politika e Cookies',
    'footer.newsletter': 'Abonohuni në Buletinin',
    'footer.newsletterDesc': 'Qëndroni të përditësuar me lajmet dhe ofertat më të fundit.',
    'footer.emailPlaceholder': 'Shkruani email-in tuaj',
    'footer.subscribe': 'Abonohu',
    'footer.rights': 'Të gjitha të drejtat e rezervuara.',
    'footer.apiStatus': 'Statusi API: Operacional',

    // Partner Modal
    'partner.title': 'Bëhu Partner',
    'partner.subtitle': 'Zgjidhni si dëshironi të lidheni me VasDream',
    'partner.agencyTitle': 'Agjenci Udhëtimi',
    'partner.agencyDesc': 'Merrni qasje në platformën tonë të rezervimeve me çmime ekskluzive B2B dhe mbështetje të dedikuar.',
    'partner.apiTitle': 'Integrim API',
    'partner.apiDesc': 'Lidhni sistemet tuaja direkt përmes XML ose JSON API për rrjedhë të automatizuar rezervimesh.',
    'partner.back': 'Kthehu te përzgjedhja',
    'partner.companyName': 'Emri i Kompanisë',
    'partner.contactName': 'Emri i Kontaktit',
    'partner.email': 'Email',
    'partner.phone': 'Telefon',
    'partner.website': 'Faqja e Internetit',
    'partner.message': 'Mesazh (Opsional)',
    'partner.submit': 'Dorëzoni Kërkesën',

    // Login Modal
    'login.title': 'Hyrje Partneri',
    'login.email': 'Email',
    'login.password': 'Fjalëkalimi',
    'login.submit': 'Hyni',
    'login.forgotPassword': 'Keni harruar fjalëkalimin?',
    'login.noAccount': 'Nuk keni llogari?',
    'login.register': 'Regjistrohuni këtu',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
